version: '3.8'

services:
  database:
    container_name: chaplin_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: chaplin
      MYSQL_DATABASE: chaplin_database
      MYSQL_USER: chaplin
      MYSQL_PASSWORD: chaplin
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: chaplin_php
    build:
      context: .
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/chaplin
    depends_on:
      - database
  nginx:
    container_name: chaplin_nginx
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/chaplin
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database