Chaplin\User\Domain\Entity\User:
  type: entity
  table: user
  id:
    id:
      type: Id

  fields:
    email:
      column: email
      type: string
      nullable: false
    roles:
      column: roles
      type: json
    password:
      column: password
      type: string
      nullable: false
    username:
      column: username
      type: string
      nullable: false

  oneToMany:
    userMovies:
      targetEntity: Chaplin\User\Domain\Entity\UserMovie
      mappedBy: user
      cascade: [ "persist" ]