Chaplin\User\Domain\Entity\User:
  type: entity
  table: user
  id:
    id:
      type: Id

  fields:
    email:
      column: email
      type: string
      nullable: false
    roles:
      column: roles
      type: json
    password:
      column: password
      type: string
      nullable: false
    username:
      column: username
      type: string
      nullable: false

  manyToMany:
    movies:
      targetEntity: Chaplin\Movie\Domain\Entity\Movie
      mappedBy: user