# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false
        bind:
            League\Tactician\CommandBus $queryBus: '@tactician.commandbus.query'
            League\Tactician\CommandBus $commandBus: '@tactician.commandbus.command'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Chaplin\:
        resource: '../src/Chaplin/'
        exclude:
            - '../src/Chaplin/DataFixtures/'

    _instanceof:
        # MAPPING HANDLER-COMMAND
        Chaplin\Core\CommandBus\CommandHandlerInterface:
            public: true
            tags:
                - { name: tactician.handler, typehints: true, bus: command }

        Chaplin\Core\CommandBus\QueryHandlerInterface:
            public: true
            tags:
                - { name: tactician.handler, typehints: true, bus: query }

    # CONTROLLER
    Chaplin\Controller\:
        resource: '../src/Chaplin/Controller/'
        tags: ['controller.service_arguments']

    # REPOSITORY
    Chaplin\Core\Infrastructure\AbstractDoctrineRepository:
        class: Chaplin\Core\Infrastructure\AbstractDoctrineRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones