Chaplin\Movie\Domain\Entity\Movie:
  type: entity
  table: movies
  id:
    id:
      type: Id

  fields:
    extId:
      column: ext_id
      type: string
      nullable: false
    title:
      column: title
      type: text
      nullable: false
    year:
      column: start_year
      type: datetime
      nullable: false
    duration:
      column: duration
      type: integer
      nullable: true

  oneToMany:
    userMovies:
      targetEntity: Colvin\User\Domain\Entity\UserMovie
      mappedBy: movie
      cascade: [ "persist" ]