doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    Quote:
                        type: yml
                        prefix: 'Chaplin\Quote\Domain'
                        dir: '%kernel.project_dir%/src/Chaplin/Quote/Infrastructure/Resources/config/doctrine'

                    User:
                        type: yml
                        prefix: 'Chaplin\User\Domain'
                        dir: '%kernel.project_dir%/src/Chaplin/User/Infrastructure/Resources/config/doctrine'